IF OBJECT_ID('dbo.PRESUPUESTO_CATEGORIA', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRESUPUESTO_CATEGORIA (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    idUsuario INT NOT NULL,
    idCategoria INT NOT NULL,
    idMoneda INT NOT NULL,
    periodo CHAR(7) NOT NULL,
    montoLimite DECIMAL(18,2) NOT NULL,
    activo BIT NOT NULL CONSTRAINT DF_PRESUPUESTO_ACTIVO DEFAULT 1,
    eliminado BIT NOT NULL CONSTRAINT DF_PRESUPUESTO_ELIMINADO DEFAULT 0,
    ipRegistro NVARCHAR(50) NULL,
    fechaRegistro DATETIME NOT NULL CONSTRAINT DF_PRESUPUESTO_FECHA_REGISTRO DEFAULT GETDATE(),
    usuarioRegistro NVARCHAR(100) NULL,
    ipModificacion NVARCHAR(50) NULL,
    fechaModificacion DATETIME NULL,
    usuarioModificacion NVARCHAR(100) NULL,
    ipEliminacion NVARCHAR(50) NULL,
    fechaEliminacion DATETIME NULL,
    usuarioEliminacion NVARCHAR(100) NULL,
    CONSTRAINT FK_PRESUPUESTO_USUARIO FOREIGN KEY (idUsuario) REFERENCES dbo.USUARIO(id),
    CONSTRAINT FK_PRESUPUESTO_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES dbo.CATEGORIA_FINANCE(id),
    CONSTRAINT FK_PRESUPUESTO_MONEDA FOREIGN KEY (idMoneda) REFERENCES dbo.MONEDA(id),
    CONSTRAINT CK_PRESUPUESTO_PERIODO CHECK (
      periodo LIKE '[1-2][0-9][0-9][0-9]-[0-1][0-9]'
      AND RIGHT(periodo, 2) BETWEEN '01' AND '12'
    ),
    CONSTRAINT CK_PRESUPUESTO_MONTO CHECK (montoLimite > 0),
    CONSTRAINT UQ_PRESUPUESTO_USUARIO_CATEGORIA_MONEDA_PERIODO
      UNIQUE (idUsuario, idCategoria, idMoneda, periodo)
  );
END;
