IF COL_LENGTH('dbo.CUENTA', 'diaCierre') IS NULL
BEGIN
  ALTER TABLE dbo.CUENTA ADD diaCierre TINYINT NULL;
END;

IF COL_LENGTH('dbo.CUENTA', 'diaPago') IS NULL
BEGIN
  ALTER TABLE dbo.CUENTA ADD diaPago TINYINT NULL;
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_CUENTA_DIA_CIERRE'
)
BEGIN
  ALTER TABLE dbo.CUENTA
    ADD CONSTRAINT CK_CUENTA_DIA_CIERRE
    CHECK (diaCierre IS NULL OR diaCierre BETWEEN 1 AND 31);
END;

IF NOT EXISTS (
  SELECT 1
  FROM sys.check_constraints
  WHERE name = 'CK_CUENTA_DIA_PAGO'
)
BEGIN
  ALTER TABLE dbo.CUENTA
    ADD CONSTRAINT CK_CUENTA_DIA_PAGO
    CHECK (diaPago IS NULL OR diaPago BETWEEN 1 AND 31);
END;
 