IF OBJECT_ID('dbo.META_AHORRO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.META_AHORRO (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    idUsuario INT NOT NULL,
    idMoneda INT NOT NULL,
    idCuenta INT NULL,
    nombre NVARCHAR(120) NOT NULL,
    descripcion NVARCHAR(300) NULL,
    montoObjetivo DECIMAL(18,2) NOT NULL,
    montoAhorrado DECIMAL(18,2) NOT NULL CONSTRAINT DF_META_AHORRADO DEFAULT 0,
    fechaObjetivo DATE NOT NULL,
    activo BIT NOT NULL CONSTRAINT DF_META_ACTIVO DEFAULT 1,
    eliminado BIT NOT NULL CONSTRAINT DF_META_ELIMINADO DEFAULT 0,
    ipRegistro NVARCHAR(50) NULL,
    fechaRegistro DATETIME NOT NULL CONSTRAINT DF_META_FECHA_REGISTRO DEFAULT GETDATE(),
    usuarioRegistro NVARCHAR(100) NULL,
    ipModificacion NVARCHAR(50) NULL,
    fechaModificacion DATETIME NULL,
    usuarioModificacion NVARCHAR(100) NULL,
    ipEliminacion NVARCHAR(50) NULL,
    fechaEliminacion DATETIME NULL,
    usuarioEliminacion NVARCHAR(100) NULL,
    CONSTRAINT FK_META_USUARIO FOREIGN KEY (idUsuario) REFERENCES dbo.USUARIO(id),
    CONSTRAINT FK_META_MONEDA FOREIGN KEY (idMoneda) REFERENCES dbo.MONEDA(id),
    CONSTRAINT FK_META_CUENTA FOREIGN KEY (idCuenta) REFERENCES dbo.CUENTA(id),
    CONSTRAINT CK_META_MONTOS CHECK (montoObjetivo > 0 AND montoAhorrado >= 0 AND montoAhorrado <= montoObjetivo)
  );
  CREATE INDEX IDX_META_USUARIO_FECHA ON dbo.META_AHORRO(idUsuario, fechaObjetivo);
END;

IF OBJECT_ID('dbo.PAGO_RECURRENTE', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PAGO_RECURRENTE (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    idUsuario INT NOT NULL,
    idCuenta INT NOT NULL,
    idCategoria INT NOT NULL,
    concepto NVARCHAR(160) NOT NULL,
    monto DECIMAL(18,2) NOT NULL,
    frecuencia NVARCHAR(15) NOT NULL,
    proximaFecha DATE NOT NULL,
    diasRecordatorio TINYINT NOT NULL CONSTRAINT DF_RECURRENTE_RECORDATORIO DEFAULT 3,
    nota NVARCHAR(500) NULL,
    activo BIT NOT NULL CONSTRAINT DF_RECURRENTE_ACTIVO DEFAULT 1,
    eliminado BIT NOT NULL CONSTRAINT DF_RECURRENTE_ELIMINADO DEFAULT 0,
    ipRegistro NVARCHAR(50) NULL,
    fechaRegistro DATETIME NOT NULL CONSTRAINT DF_RECURRENTE_FECHA_REGISTRO DEFAULT GETDATE(),
    usuarioRegistro NVARCHAR(100) NULL,
    ipModificacion NVARCHAR(50) NULL,
    fechaModificacion DATETIME NULL,
    usuarioModificacion NVARCHAR(100) NULL,
    ipEliminacion NVARCHAR(50) NULL,
    fechaEliminacion DATETIME NULL,
    usuarioEliminacion NVARCHAR(100) NULL,
    CONSTRAINT FK_RECURRENTE_USUARIO FOREIGN KEY (idUsuario) REFERENCES dbo.USUARIO(id),
    CONSTRAINT FK_RECURRENTE_CUENTA FOREIGN KEY (idCuenta) REFERENCES dbo.CUENTA(id),
    CONSTRAINT FK_RECURRENTE_CATEGORIA FOREIGN KEY (idCategoria) REFERENCES dbo.CATEGORIA_FINANCE(id),
    CONSTRAINT CK_RECURRENTE_MONTO CHECK (monto > 0),
    CONSTRAINT CK_RECURRENTE_FRECUENCIA CHECK (frecuencia IN ('SEMANAL', 'MENSUAL', 'ANUAL')),
    CONSTRAINT CK_RECURRENTE_RECORDATORIO CHECK (diasRecordatorio BETWEEN 0 AND 30)
  );
  CREATE INDEX IDX_RECURRENTE_USUARIO_FECHA ON dbo.PAGO_RECURRENTE(idUsuario, proximaFecha);
END;
